version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: king-jawir-web
    ports:
      - '4101:4101'
    environment:
      - NODE_ENV=production
      - API_URL=http://api:4102
    networks:
      - king-jawir-network
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: king-jawir-api
    ports:
      - '4102:4102'
    environment:
      - NODE_ENV=production
    networks:
      - king-jawir-network
    restart: unless-stopped

networks:
  king-jawir-network:
    driver: bridge
