version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./apps/nginx/Dockerfile
    container_name: king-jawir-nginx
    ports:
      - '4104:80'
    networks:
      - king-jawir-network
    depends_on:
      - web
      - api
      - scraper
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: king-jawir-web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api
    networks:
      - king-jawir-network
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: king-jawir-api
    environment:
      - NODE_ENV=production
      - SCRAPER_URL=http://scraper:4103
    networks:
      - king-jawir-network
    depends_on:
      - scraper
    restart: unless-stopped

  scraper:
    build:
      context: .
      dockerfile: ./apps/scraper/Dockerfile
    container_name: king-jawir-scraper
    networks:
      - king-jawir-network
    restart: unless-stopped

networks:
  king-jawir-network:
    driver: bridge
